services:
  postgres:
    image: ankane/pgvector:latest
    container_name: innjobtracker-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: jobtracker-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin
  python:
    build:
      context: ./python-embedding 
    container_name: jobtracker-python
    working_dir: /app
    environment:
      PYTHONUNBUFFERED: 1
      EMBEDDING_MODEL: sentence-transformers/all-mpnet-base-v2
    volumes:
      - ./ml:/app
    depends_on:
      - postgres
  spring:
    build:
      context: ./user-service
    image: openjdk:17-jdk-slim
    container_name: jobtracker-spring
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_BUCKET: ${SUPABASE_BUCKET}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      SUPABASE_PUBLIC_KEY: ${SUPABASE_PUBLIC_KEY}
    working_dir: /app/user-service
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin_data:
